### ISSUE TITLE
Nová verze nette

### ISSUE THREAD

**Issue by patrickkusebauch** [chapcz/chap-adminlte#4]
Ahoj,
je nějaká šance upgradu na novou verzi Nette?
Nebo celkově nějakého vývoje ohledně totohle doplňku?

**Comment by chapcz** [comment]
Ahoj, v dohledné době na to bohužel nemám prostor. Nicméně případné PR jsou vítány.

**Comment by chapcz** [comment]
nyní podporuje Nette 3.0

**Comment by patrickkusebauch** [comment]
:+1:
